### ISSUE TITLE
up 的时候报错：permission denied, open /home/yapi/log/

### ISSUE THREAD

**Issue by judasn** [branchzero/yapi-docker#5]
```
mongodb_1  | 2018-03-07T02:06:33.827+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=2047ba75e473
mongodb_1  | 2018-03-07T02:06:33.829+0000 I CONTROL  [initandlisten] db version v3.5.13
mongodb_1  | 2018-03-07T02:06:33.829+0000 I CONTROL  [initandlisten] git version: 52bbaa007cd84631d6da811d9a05b59f2dfad4f3
mongodb_1  | 2018-03-07T02:06:33.829+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1t  3 May 2016
mongodb_1  | 2018-03-07T02:06:33.829+0000 I CONTROL  [initandlisten] allocator: tcmalloc
mongodb_1  | 2018-03-07T02:06:33.829+0000 I CONTROL  [initandlisten] modules: none
mongodb_1  | 2018-03-07T02:06:33.829+0000 I CONTROL  [initandlisten] build environment:
mongodb_1  | 2018-03-07T02:06:33.829+0000 I CONTROL  [initandlisten]     distmod: debian81
mongodb_1  | 2018-03-07T02:06:33.829+0000 I CONTROL  [initandlisten]     distarch: x86_64
mongodb_1  | 2018-03-07T02:06:33.829+0000 I CONTROL  [initandlisten]     target_arch: x86_64
mongodb_1  | 2018-03-07T02:06:33.829+0000 I CONTROL  [initandlisten] options: { net: { bindIpAll: true } }
mongodb_1  | 2018-03-07T02:06:33.836+0000 I STORAGE  [initandlisten] 
mongodb_1  | 2018-03-07T02:06:33.836+0000 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
mongodb_1  | 2018-03-07T02:06:33.836+0000 I STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
mongodb_1  | 2018-03-07T02:06:33.837+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=407M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
mongodb_1  | 2018-03-07T02:06:36.642+0000 I CONTROL  [initandlisten] 
mongodb_1  | 2018-03-07T02:06:36.646+0000 I CONTROL  [initandlisten] ** NOTE: This is a development version (3.5.13) of MongoDB.
mongodb_1  | 2018-03-07T02:06:36.646+0000 I CONTROL  [initandlisten] **       Not recommended for production.
mongodb_1  | 2018-03-07T02:06:36.646+0000 I CONTROL  [initandlisten] 
mongodb_1  | 2018-03-07T02:06:36.646+0000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
mongodb_1  | 2018-03-07T02:06:36.646+0000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
mongodb_1  | 2018-03-07T02:06:36.646+0000 I CONTROL  [initandlisten] 
mongodb_1  | 2018-03-07T02:06:36.646+0000 I CONTROL  [initandlisten] 
mongodb_1  | 2018-03-07T02:06:36.646+0000 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
mongodb_1  | 2018-03-07T02:06:36.646+0000 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
mongodb_1  | 2018-03-07T02:06:36.646+0000 I CONTROL  [initandlisten] 
mongodb_1  | 2018-03-07T02:06:36.646+0000 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/defrag is 'always'.
mongodb_1  | 2018-03-07T02:06:36.646+0000 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
mongodb_1  | 2018-03-07T02:06:36.646+0000 I CONTROL  [initandlisten] 
mongodb_1  | 2018-03-07T02:06:36.743+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
mongodb_1  | 2018-03-07T02:06:36.782+0000 I COMMAND  [initandlisten] setting featureCompatibilityVersion to 3.6
mongodb_1  | 2018-03-07T02:06:36.782+0000 I NETWORK  [initandlisten] waiting for connections on port 27017
web_1      | 
web_1      | > yapi@1.3.6 install-server /home/yapi/yapi
web_1      | >  node server/install.js
web_1      | 
mongodb_1  | 2018-03-07T02:06:37.743+0000 I NETWORK  [listener] connection accepted from 172.18.0.3:38654 #1 (1 connection now open)
mongodb_1  | 2018-03-07T02:06:37.765+0000 I NETWORK  [conn1] received client metadata from 172.18.0.3:38654 conn: { driver: { name: "nodejs", version: "2.2.11" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "3.10.0-693.el7.x86_64" }, platform: "Node.js v8.9.0, LE, mongodb-core: 2.0.13" }
web_1      | log: mongodb load success...
web_1      | (node:26) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: EACCES: permission denied, open '/home/yapi/log/2018-3.log'
web_1      | (node:26) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
mongodb_1  | 2018-03-07T02:06:37.791+0000 I NETWORK  [listener] connection accepted from 172.18.0.3:38656 #2 (2 connections now open)
mongodb_1  | 2018-03-07T02:06:37.800+0000 I NETWORK  [listener] connection accepted from 172.18.0.3:38658 #3 (3 connections now open)
mongodb_1  | 2018-03-07T02:06:37.800+0000 I NETWORK  [listener] connection accepted from 172.18.0.3:38660 #4 (4 connections now open)
mongodb_1  | 2018-03-07T02:06:37.800+0000 I NETWORK  [listener] connection accepted from 172.18.0.3:38662 #5 (5 connections now open)
mongodb_1  | 2018-03-07T02:06:37.895+0000 I INDEX    [conn1] build index on: yapi.user properties: { v: 2, key: { username: 1 }, name: "username_1", ns: "yapi.user" }
mongodb_1  | 2018-03-07T02:06:37.895+0000 I INDEX    [conn1] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
mongodb_1  | 2018-03-07T02:06:37.897+0000 I INDEX    [conn1] build index done.  scanned 0 total records. 0 secs
mongodb_1  | 2018-03-07T02:06:37.959+0000 I INDEX    [conn1] build index on: yapi.user properties: { v: 2, unique: true, key: { email: 1 }, name: "email_1", ns: "yapi.user" }
mongodb_1  | 2018-03-07T02:06:37.959+0000 I INDEX    [conn1] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
mongodb_1  | 2018-03-07T02:06:37.961+0000 I INDEX    [conn1] build index done.  scanned 0 total records. 0 secs
mongodb_1  | 2018-03-07T02:06:37.961+0000 I COMMAND  [conn3] command yapi.identitycounters command: insert { insert: "identitycounters", ordered: false, writeConcern: { w: 1 }, $db: "yapi" } ninserted:1 keysInserted:1 numYields:0 reslen:44 locks:{ Global: { acquireCount: { r: 3, w: 3 } }, Database: { acquireCount: { w: 2, W: 1 }, acquireWaitCount: { w: 2 }, timeAcquiringMicros: { w: 104869 } }, Collection: { acquireCount: { w: 2 } } } protocol:op_query 148ms
mongodb_1  | 2018-03-07T02:06:38.026+0000 I INDEX    [conn1] build index on: yapi.project properties: { v: 2, key: { uid: 1 }, name: "uid_1", ns: "yapi.project" }
mongodb_1  | 2018-03-07T02:06:38.026+0000 I INDEX    [conn1] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
mongodb_1  | 2018-03-07T02:06:38.028+0000 I INDEX    [conn1] build index done.  scanned 0 total records. 0 secs
mongodb_1  | 2018-03-07T02:06:38.086+0000 I INDEX    [conn1] build index on: yapi.project properties: { v: 2, key: { name: 1 }, name: "name_1", ns: "yapi.project" }
mongodb_1  | 2018-03-07T02:06:38.086+0000 I INDEX    [conn1] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
mongodb_1  | 2018-03-07T02:06:38.087+0000 I INDEX    [conn1] build index done.  scanned 0 total records. 0 secs
mongodb_1  | 2018-03-07T02:06:38.116+0000 I INDEX    [conn1] build index on: yapi.project properties: { v: 2, key: { group_id: 1 }, name: "group_id_1", ns: "yapi.project" }
mongodb_1  | 2018-03-07T02:06:38.116+0000 I INDEX    [conn1] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
mongodb_1  | 2018-03-07T02:06:38.117+0000 I INDEX    [conn1] build index done.  scanned 0 total records. 0 secs
mongodb_1  | 2018-03-07T02:06:38.172+0000 I INDEX    [conn1] build index on: yapi.log properties: { v: 2, key: { uid: 1 }, name: "uid_1", ns: "yapi.log" }
mongodb_1  | 2018-03-07T02:06:38.172+0000 I INDEX    [conn1] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
mongodb_1  | 2018-03-07T02:06:38.173+0000 I INDEX    [conn1] build index done.  scanned 0 total records. 0 secs
mongodb_1  | 2018-03-07T02:06:38.193+0000 I INDEX    [conn1] build index on: yapi.log properties: { v: 2, key: { typeid: 1, type: 1 }, name: "typeid_1_type_1", ns: "yapi.log" }
mongodb_1  | 2018-03-07T02:06:38.193+0000 I INDEX    [conn1] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
mongodb_1  | 2018-03-07T02:06:38.195+0000 I INDEX    [conn1] build index done.  scanned 0 total records. 0 secs
mongodb_1  | 2018-03-07T02:06:38.253+0000 I INDEX    [conn1] build index on: yapi.interface_col properties: { v: 2, key: { uid: 1 }, name: "uid_1", ns: "yapi.interface_col" }
mongodb_1  | 2018-03-07T02:06:38.253+0000 I INDEX    [conn1] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
mongodb_1  | 2018-03-07T02:06:38.255+0000 I INDEX    [conn1] build index done.  scanned 0 total records. 0 secs
mongodb_1  | 2018-03-07T02:06:38.276+0000 I INDEX    [conn1] build index on: yapi.interface_col properties: { v: 2, key: { project_id: 1 }, name: "project_id_1", ns: "yapi.interface_col" }
mongodb_1  | 2018-03-07T02:06:38.276+0000 I INDEX    [conn1] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
mongodb_1  | 2018-03-07T02:06:38.277+0000 I INDEX    [conn1] build index done.  scanned 0 total records. 0 secs
mongodb_1  | 2018-03-07T02:06:38.331+0000 I INDEX    [conn1] build index on: yapi.interface_cat properties: { v: 2, key: { uid: 1 }, name: "uid_1", ns: "yapi.interface_cat" }
mongodb_1  | 2018-03-07T02:06:38.331+0000 I INDEX    [conn1] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
mongodb_1  | 2018-03-07T02:06:38.332+0000 I INDEX    [conn1] build index done.  scanned 0 total records. 0 secs
mongodb_1  | 2018-03-07T02:06:38.352+0000 I INDEX    [conn1] build index on: yapi.interface_cat properties: { v: 2, key: { project_id: 1 }, name: "project_id_1", ns: "yapi.interface_cat" }
mongodb_1  | 2018-03-07T02:06:38.352+0000 I INDEX    [conn1] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
mongodb_1  | 2018-03-07T02:06:38.354+0000 I INDEX    [conn1] build index done.  scanned 0 total records. 0 secs
mongodb_1  | 2018-03-07T02:06:38.407+0000 I INDEX    [conn1] build index on: yapi.interface_case properties: { v: 2, key: { uid: 1 }, name: "uid_1", ns: "yapi.interface_case" }
mongodb_1  | 2018-03-07T02:06:38.407+0000 I INDEX    [conn1] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
mongodb_1  | 2018-03-07T02:06:38.408+0000 I INDEX    [conn1] build index done.  scanned 0 total records. 0 secs
mongodb_1  | 2018-03-07T02:06:38.426+0000 I INDEX    [conn1] build index on: yapi.interface_case properties: { v: 2, key: { col_id: 1 }, name: "col_id_1", ns: "yapi.interface_case" }
mongodb_1  | 2018-03-07T02:06:38.426+0000 I INDEX    [conn1] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
mongodb_1  | 2018-03-07T02:06:38.428+0000 I INDEX    [conn1] build index done.  scanned 0 total records. 0 secs
mongodb_1  | 2018-03-07T02:06:38.447+0000 I INDEX    [conn1] build index on: yapi.interface_case properties: { v: 2, key: { project_id: 1 }, name: "project_id_1", ns: "yapi.interface_case" }
mongodb_1  | 2018-03-07T02:06:38.447+0000 I INDEX    [conn1] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
mongodb_1  | 2018-03-07T02:06:38.449+0000 I INDEX    [conn1] build index done.  scanned 0 total records. 0 secs
mongodb_1  | 2018-03-07T02:06:38.498+0000 I INDEX    [conn1] build index on: yapi.interface properties: { v: 2, key: { uid: 1 }, name: "uid_1", ns: "yapi.interface" }
mongodb_1  | 2018-03-07T02:06:38.498+0000 I INDEX    [conn1] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
mongodb_1  | 2018-03-07T02:06:38.499+0000 I INDEX    [conn1] build index done.  scanned 0 total records. 0 secs
mongodb_1  | 2018-03-07T02:06:38.517+0000 I INDEX    [conn1] build index on: yapi.interface properties: { v: 2, key: { path: 1, method: 1 }, name: "path_1_method_1", ns: "yapi.interface" }
mongodb_1  | 2018-03-07T02:06:38.517+0000 I INDEX    [conn1] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
mongodb_1  | 2018-03-07T02:06:38.518+0000 I INDEX    [conn1] build index done.  scanned 0 total records. 0 secs
mongodb_1  | 2018-03-07T02:06:38.533+0000 I INDEX    [conn1] build index on: yapi.interface properties: { v: 2, key: { project_id: 1 }, name: "project_id_1", ns: "yapi.interface" }
mongodb_1  | 2018-03-07T02:06:38.533+0000 I INDEX    [conn1] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
mongodb_1  | 2018-03-07T02:06:38.535+0000 I INDEX    [conn1] build index done.  scanned 0 total records. 0 secs
mongodb_1  | 2018-03-07T02:06:38.583+0000 I INDEX    [conn1] build index on: yapi.group properties: { v: 2, key: { uid: 1 }, name: "uid_1", ns: "yapi.group" }
mongodb_1  | 2018-03-07T02:06:38.583+0000 I INDEX    [conn1] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
mongodb_1  | 2018-03-07T02:06:38.584+0000 I INDEX    [conn1] build index done.  scanned 0 total records. 0 secs
mongodb_1  | 2018-03-07T02:06:38.601+0000 I INDEX    [conn1] build index on: yapi.group properties: { v: 2, key: { group_name: 1 }, name: "group_name_1", ns: "yapi.group" }
mongodb_1  | 2018-03-07T02:06:38.601+0000 I INDEX    [conn1] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
mongodb_1  | 2018-03-07T02:06:38.602+0000 I INDEX    [conn1] build index done.  scanned 0 total records. 0 secs
mongodb_1  | 2018-03-07T02:06:38.650+0000 I INDEX    [conn1] build index on: yapi.avatar properties: { v: 2, key: { uid: 1 }, name: "uid_1", ns: "yapi.avatar" }
mongodb_1  | 2018-03-07T02:06:38.650+0000 I INDEX    [conn1] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
mongodb_1  | 2018-03-07T02:06:38.651+0000 I INDEX    [conn1] build index done.  scanned 0 total records. 0 secs
mongodb_1  | 2018-03-07T02:06:38.701+0000 I INDEX    [conn1] build index on: yapi.token properties: { v: 2, key: { project_id: 1 }, name: "project_id_1", ns: "yapi.token" }
mongodb_1  | 2018-03-07T02:06:38.701+0000 I INDEX    [conn1] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
mongodb_1  | 2018-03-07T02:06:38.702+0000 I INDEX    [conn1] build index done.  scanned 0 total records. 0 secs
mongodb_1  | 2018-03-07T02:06:38.751+0000 I INDEX    [conn1] build index on: yapi.follow properties: { v: 2, key: { uid: 1 }, name: "uid_1", ns: "yapi.follow" }
mongodb_1  | 2018-03-07T02:06:38.751+0000 I INDEX    [conn1] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
mongodb_1  | 2018-03-07T02:06:38.752+0000 I INDEX    [conn1] build index done.  scanned 0 total records. 0 secs
mongodb_1  | 2018-03-07T02:06:38.771+0000 I INDEX    [conn1] build index on: yapi.follow properties: { v: 2, key: { project_id: 1 }, name: "project_id_1", ns: "yapi.follow" }
mongodb_1  | 2018-03-07T02:06:38.771+0000 I INDEX    [conn1] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
mongodb_1  | 2018-03-07T02:06:38.772+0000 I INDEX    [conn1] build index done.  scanned 0 total records. 0 secs
web_1      | 初始化管理员账号成功,账号名："admin@admin.com"，密码："ymfe.org"
mongodb_1  | 2018-03-07T02:06:38.781+0000 I NETWORK  [conn3] end connection 172.18.0.3:38658 (4 connections now open)
mongodb_1  | 2018-03-07T02:06:38.781+0000 I NETWORK  [conn4] end connection 172.18.0.3:38660 (4 connections now open)
mongodb_1  | 2018-03-07T02:06:38.782+0000 I NETWORK  [conn5] end connection 172.18.0.3:38662 (4 connections now open)
mongodb_1  | 2018-03-07T02:06:38.782+0000 I NETWORK  [conn2] end connection 172.18.0.3:38656 (4 connections now open)
mongodb_1  | 2018-03-07T02:06:38.782+0000 I NETWORK  [conn1] end connection 172.18.0.3:38654 (1 connection now open)
web_1      | touch: cannot touch '/home/yapi/log/init.lock': Permission denied
web_1      | 
web_1      | > yapi@1.3.6 start /home/yapi/yapi
web_1      | >  node server/app.js
web_1      | 
web_1      | log: the server is start at 127.0.0.1:3000
web_1      | fs.js:646
web_1      |   return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
web_1      |                  ^
web_1      | 
web_1      | Error: EACCES: permission denied, open '/home/yapi/log/2018-3.log'
web_1      |     at Object.fs.openSync (fs.js:646:18)
web_1      |     at Object.fs.writeFileSync (fs.js:1291:33)
web_1      |     at Object.exports.log (/home/yapi/yapi/server/utils/commons.js:73:6)
web_1      |     at Object.<anonymous> (/home/yapi/yapi/server/app.js:60:9)
web_1      |     at Module._compile (module.js:635:30)
web_1      |     at Object.Module._extensions..js (module.js:646:10)
web_1      |     at Module.load (module.js:554:32)
web_1      |     at tryModuleLoad (module.js:497:12)
web_1      |     at Function.Module._load (module.js:489:3)
web_1      |     at Function.Module.runMain (module.js:676:10)
web_1      |     at startup (bootstrap_node.js:187:16)
web_1      |     at bootstrap_node.js:608:3
web_1      | npm ERR! code ELIFECYCLE
web_1      | npm ERR! errno 1
web_1      | npm ERR! yapi@1.3.6 start: ` node server/app.js`
web_1      | npm ERR! Exit status 1
web_1      | npm ERR! 
web_1      | npm ERR! Failed at the yapi@1.3.6 start script.
web_1      | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
web_1      | 
web_1      | npm ERR! A complete log of this run can be found in:
web_1      | npm ERR!     /home/yapi/.npm/_logs/2018-03-07T02_06_39_844Z-debug.log
yapidocker_web_1 exited with code 1

```

**Comment by judasn** [comment]
解决办法：`chmod -R 777 /opt/git-data/yapi-docker`
